### ISSUE TITLE
bidirectional?

### ISSUE THREAD

**Issue by Xiaobin-Rong** [lucidrains/minGRU-pytorch#10]
Hi, thanks for your implementation. I wonder if the minGRU will support bidirectional setting?

**Comment by lucidrains** [comment]
@Xiaobin-Rong hey Rong, you can easily achieve this with `torch.flip`

what is your use case?

**Comment by Xiaobin-Rong** [comment]
@lucidrains  Well, I consider sequence modeling cases, such as translation. In translation, the current token is dependent not only on past tokens but also on future ones. Thus, a bidirectional setting will enable the minGRU to predict the current token while considering future information.

**Comment by lucidrains** [comment]
@Xiaobin-Rong yea sounds good, make sense

you can just use [`torch.flip`](https://pytorch.org/docs/stable/generated/torch.flip.html) then

**Comment by Xiaobin-Rong** [comment]
@lucidrains  ok, thanks for your response
