### ISSUE TITLE
how to set hidden_size?

### ISSUE THREAD

**Issue by shenbuguanni** [lucidrains/minGRU-pytorch#11]
May I ask whether the current version supports the setting of hidden_size of minGRU. Thanks

**Comment by lucidrains** [comment]
@shenbuguanni you just have to set the [expansion factor](https://github.com/lucidrains/minGRU-pytorch/blob/main/minGRU_pytorch/minGRU.py#L31) to be not equal to 1.

hidden size will be `dim * expansion_factor`

**Comment by shenbuguanni** [comment]
my input_dim=32 and set expansion_factor=2.0 , but the output dim is 32 which same as input_dim.

**Comment by lucidrains** [comment]
it automatically projects it back to input dimension at the end
