### ISSUE TITLE
Not passing `prev_hiddens` to model forward in `base_decoding` ?

### ISSUE THREAD

**Issue by gcanat** [lucidrains/minGRU-pytorch#12]
Hey,
I was wondering if it is intended that `prev_hiddens` is not passed to the model forward in `base_deconding` ?

Something like this maybe:
```diff
    prev_hiddens = None

    for _ in range(sample_num_times):
-      logits, prev_hiddens = net(out, return_prev_hiddens = True)
+      logits, prev_hiddens = net(out, return_prev_hiddens = True, prev_hiddens=prev_hiddens)
```
But maybe I misunderstood something.

**Comment by lucidrains** [comment]
ah yes, you can pass that in as long as you don't have the convolutions

**Comment by lucidrains** [comment]
I'll make it automatic tomorrow morning

**Comment by lucidrains** [comment]
@gcanat should be resolved

**Comment by gcanat** [comment]
wonderful, thanks!
