### ISSUE TITLE
minLSTM implementation

### ISSUE THREAD

**Issue by crlandsc** [lucidrains/minGRU-pytorch#2]
Thank you so much for this implementation! Are you planning to also implement the minLSTM from the paper as well?

**Comment by lucidrains** [comment]
hey Christopher

probably not, i was mainly interested in `minGRU` for its simplicity

**Comment by crlandsc** [comment]
Understandable. Well again, thanks for this implementation!

**Comment by lucidrains** [comment]
yup, no problem!
