### ISSUE TITLE
Recurrence

### ISSUE THREAD

**Issue by TheGullahanMaster** [lucidrains/minGRU-pytorch#4]
Hi, how would one use recurrence in the supplied train.py? It seems to me it's sampled like a transformer would be, appending output to input sequence and then feeding the whole lot into the model to get more.
Thanks in Advance

**Comment by lucidrains** [comment]
@TheGullahanMaster hey, decided to just show the full example, should be self explanatory

**Comment by lucidrains** [comment]
@TheGullahanMaster going to just disable the caching for the version with the conv, as it is not really the meat of the paper
