### ISSUE TITLE
Does this implementation handle the vanishing gradient problem?

### ISSUE THREAD

**Issue by ParikhKadam** [lucidrains/minGRU-pytorch#8]
We all know RNNs have this problem. While the paper "Were RNNs All We Needed?" focuses on parallelism, does it also lay down any changes to handle vanishing gradients?

Just curious.

**Comment by dame-cell** [comment]
I'm assuming since the authors remove the previous hidden state dependencies from the gates, which simplifies the model and reduces the number of parameters .this somehow helps with the vanishing gradients

**Comment by lucidrains** [comment]
> I'm assuming since the authors remove the previous hidden state dependencies from the gates, which simplifies the model and reduces the number of parameters .this somehow helps with the vanishing gradients

yes exactly, and also there is not a nonlinearity (usually a tanh) as the hidden state propagates along the sequence dimension, which is the reason it can be parallelized with the associative scan (here formalized in log space with heinsen)

this comes with its [own costs](https://arxiv.org/abs/2404.08819) however

if you wish to have a "real" simplified RNN, take a look at [this repo](https://github.com/lucidrains/light-recurrent-unit-pytorch)
