### ISSUE TITLE
Discrepancy between the results of parallel and sequential execution

### ISSUE THREAD

**Issue by gbrlfaria** [lucidrains/minGRU-pytorch#9]
The output of the minGRU layer differs depending on whether sequential or parallel execution is used. Consider the following example.

```py
import torch
from minGRU_pytorch import minGRU

# disable grads and set seed
torch.set_grad_enabled(False)
torch.manual_seed(0)

# initialize model
mingru = minGRU(dim=4)

# initialize dummy data
dummy_x = torch.randn((1, 3, 4))
dummy_h0 = torch.rand((1, 1, 4))

# parallel execution
y_par = mingru.forward(x=dummy_x, prev_hidden=dummy_h0)

print(y_par)

# sequential execution
y_seq = []
h = dummy_h0
for i in range(3):
    x = dummy_x[:, i, None, :]
    y, h = mingru.forward(x=x, prev_hidden=h, return_next_prev_hidden=True)
    y_seq.append(y)
y_seq = torch.cat(y_seq, dim=1)

print(y_seq)

# in particular when h0 = 0 (if we accept 0 is a possibility)
print(torch.allclose(
    mingru(x=dummy_x, prev_hidden=None),
    mingru(x=dummy_x, prev_hidden=torch.zeros((1, 1, 4)))
))

```

Output:
```
tensor([[[1.3748, 0.5258, 0.7738, 0.7670],
         [0.8969, 0.8045, 0.6236, 0.5518],
         [1.4590, 0.5974, 0.7648, 0.5027]]])
tensor([[[1.2011, 0.2240, 0.5685, 0.4741],
         [0.8110, 0.7151, 0.5268, 0.3944],
         [1.4364, 0.5614, 0.7124, 0.4118]]])
False
```

The only scenario in which the results of parallel and sequential execution agree with each other is when `prev_hidden=None`.

Upon further inspection, it seems that there might be a mistake in Line 4 of Algorithm 6 of the original paper (https://arxiv.org/pdf/2410.01201). According to Equations 6 and 7 of the parallel scan paper (https://arxiv.org/pdf/2311.06281), `logcumsumexp` should be applied to the log of $h_0$, not to $\log(g(h_0))$. So, Line 4 of the algorithm should read something like $\text{log h}_0 \gets \log(h_0)$.

In fact, setting `torch.log(prev_hidden)` instead of `log_g(prev_hidden)` makes this discrepancy disappear, and introduces no issues even when $h_0$ is all zeros (edit: likely due to the fact that, in pytorch, `log(0.0) = -inf` and `exp(-inf) = 0.0`).

Can you confirm this?

**Comment by lucidrains** [comment]
@gbrlfaria hey Gabriel, i think you are right and will just make the change

pinging @leofeng-ca for a double check, and for potentially correcting the paper

**Comment by lucidrains** [comment]
@gbrlfaria  i don't think it is an error in the paper, as the paper probably assumes that the previous hiddens are `inv_g` transformed

we'll keep the `prev_hiddens` under the `g` transformation in this repo, however, as it does not make sense to do more calculations than needed
